packages:
  - apps/*
  - packages/*
  - run

catalog:
  "@ant-design/pro-components": ^2.8.9
  "@types/node": ^25.0.3
  "@clack/prompts": ^0.11.0
  "@umijs/max": 4.6.13
  "@umijs/lint": 4.6.13
  child_process: ^1.0.2
  cross-env: ^10.0.0
  fs: 0.0.1-security
  unbuild: ^3.6.1
  umi-presets-pro: ^2.0.3
  path: ^0.12.7
  react: "^19.1.0"
  react-dom: "^19.1.0"
  turbo: ^2.6.3
  typescript: ^5.6.3
