packages:
  - apps/*
  - packages/*
  - run

catalog:
  '@types/node': ^25.0.3
  '@clack/prompts': ^0.11.0
  child_process: ^1.0.2
  fs: 0.0.1-security
  '@umijs/max': 4.6.13
  unbuild: ^3.6.1
  path: ^0.12.7
  turbo: ^2.6.3
  typescript: ^5.0.3
